import React from 'react';
import { MdOutlineArrowOutward } from "react-icons/md";

function Footer() {
  return (
    <div className="bg-[#f5f5f7] text-[#6e6e73] text-[12px] px-4 py-8">
      <div className="max-w-[980px] mx-auto space-y-8">
        {/* Quick Links Section */}
        <div>
          <h2 className="text-black text-xl font-semibold mb-4">Quick Links</h2>
          <div className="flex flex-wrap gap-3">
            <button className="border border-[#d2d2d7] rounded-full px-4 py-2 flex items-center gap-1 hover:bg-[#e5e5ea] transition">
              Find a Store <MdOutlineArrowOutward className="text-[13px]" />
            </button>
            <button className="border border-[#d2d2d7] rounded-full px-4 py-2 flex items-center gap-1 hover:bg-[#e5e5ea] transition">
              Order Status <MdOutlineArrowOutward className="text-[13px]" />
            </button>
            <button className="border border-[#d2d2d7] rounded-full px-4 py-2 flex items-center gap-1 hover:bg-[#e5e5ea] transition">
              Shopping Help <MdOutlineArrowOutward className="text-[13px]" />
            </button>
            <button className="border border-[#d2d2d7] rounded-full px-4 py-2 flex items-center gap-1 hover:bg-[#e5e5ea] transition">
              Returns <MdOutlineArrowOutward className="text-[13px]" />
            </button>
            <button className="border border-[#d2d2d7] rounded-full px-4 py-2 flex items-center gap-1 hover:bg-[#e5e5ea] transition">
              Your Saves <MdOutlineArrowOutward className="text-[13px]" />
            </button>
          </div>
        </div>
        <div className="space-y-3">
          <p>° Get extra trade-in credit when you trade in an eligible iPhone and purchase a new eligible Apple device through June 18, 2025. Additional terms from Apple or Apple’s trade-in partners may apply.</p>
          <p>∆ Apple Intelligence is available in beta on all iPhone 16 models, iPhone 15 Pro, iPhone 15 Pro Max, iPad mini (A17 Pro), and iPad and Mac models with M1 and later, with Siri and device language set to Chinese (Simplified), English (Australia, Canada, India, Ireland, New Zealand, Singapore, South Africa, UK or US), French, German, Italian, Japanese, Korean, Portuguese (Brazil) or Spanish, as part of an iOS 18, iPadOS 18 and macOS Sequoia software update, with more languages coming over the course of the year, including Vietnamese. Some features may not be available in all regions or languages.</p>
          <p>*Pricing for iPhone 16 and iPhone 16 Plus includes a $30 connectivity discount that requires activation with AT&T, Boost Mobile, T-Mobile, or Verizon. Financing available to qualified customers, subject to credit approval and credit limit, and requires you to select Citizens One Apple iPhone Payments or Apple Card Monthly Installments (ACMI) as your payment type at checkout at Apple. You’ll need to select AT&T, Boost Mobile, T‑Mobile, or Verizon as your carrier when you checkout. An iPhone purchased with ACMI is always unlocked, so you can switch carriers at any time, subject to your carrier’s terms. Taxes and shipping on items purchased using ACMI are subject to your card’s variable APR, not the ACMI 0% APR. ACMI is not available for purchases made online at special storefronts. The last month’s payment for each product will be the product’s purchase price, less all other payments at the monthly payment amount. ACMI financing is subject to change at any time for any reason, including but not limited to, installment term lengths and eligible products. See the Apple Card Customer Agreement(Opens in a new window) for more information about ACMI. Additional Citizens One Apple iPhone Payments terms are here(Opens in a new window).</p>
          <p>◊ Apple Card Monthly Installments (ACMI) is a 0% APR payment option that is only available if you select it at checkout in the U.S. for eligible products purchased at Apple Store locations, apple.com(Opens in a new window), the Apple Store app, or by calling 1-800-MY-APPLE, and is subject to credit approval and credit limit. See support.apple.com/102730(Opens in a new window) for more information about eligible products. Existing customers: See your Customer Agreement for your variable APR. As of January 1, 2025, the variable APR on new Apple Card accounts ranges from 18.24% to 28.49%. You must elect to use ACMI at checkout. If you buy an ACMI-eligible product with a one-time payment on Apple Card at checkout, that purchase is subject to your Apple Card’s variable APR, not the ACMI 0% APR. Taxes and shipping on items purchased using ACMI are subject to your Apple Card’s variable APR, not the ACMI 0% APR. In order to buy an iPhone with ACMI, you must select one of the following carriers: AT&T, Boost Mobile, T-Mobile, or Verizon. An iPhone purchased with ACMI is always unlocked, so you can switch carriers at any time, subject to your carrier’s terms. ACMI is not available for purchases made online at the following special stores: Apple Employee Purchase Plan; participating corporate Employee Purchase Programs; Apple at Work for small businesses; Government and Veterans and Military Purchase Programs; or on refurbished devices. The last month’s payment for each product will be the product’s purchase price, less all other payments at the monthly payment amount. ACMI is subject to change at any time for any reason, including but not limited to installment term lengths and eligible products. See the Apple Card Customer Agreement(Opens in a new window) for more information about ACMI.</p>
          <p>To access and use all Apple Card features and products available only to Apple Card users, you must add Apple Card to Wallet on an iPhone or iPad that supports and has the latest version of iOS or iPadOS. Apple Card is subject to credit approval, available only for qualifying applicants in the United States, and issued by Goldman Sachs Bank USA, Salt Lake City Branch.</p>
          <p>Apple Payments Services LLC, a subsidiary of Apple Inc., is a service provider of Goldman Sachs Bank USA for Apple Card and Savings accounts. Neither Apple Inc. nor Apple Payments Services LLC is a bank.</p>
          <p>If you reside in the U.S. territories, please call Goldman Sachs at 877-255-5923 with questions about Apple Card.</p>
          <p>† Monthly pricing is available when you select Apple Card Monthly Installments (ACMI) as payment type at checkout at Apple, and is subject to credit approval and credit limit. Financing terms vary by product. Taxes and shipping are not included in ACMI and are subject to your card’s variable APR. See the Apple Card Customer Agreement(Opens in a new window) for more information. ACMI is not available for purchases made online at special storefronts. The last month’s payment for each product will be the product’s purchase price, less all other payments at the monthly payment amount. ACMI financing is subject to change at any time for any reason, including but not limited to, installment term lengths and eligible products. See support.apple.com/kb/HT211204(Opens in a new window) for information about upcoming changes to ACMI financing.</p>
          <p>1. Special pricing available to qualified customers. To learn more about how to start qualifying toward special pricing, talk to an Apple Specialist in a store or give us a call at 1‑800‑MY‑APPLE.</p>
          <p>2. $9 two-hour delivery on eligible Apple products in most metros. Offer is not available on customized Mac, engraved products, and for certain order types including orders paid for with financing or by bank transfer. Delivery times vary according to your selected delivery address, availability of your items, and the time of day you place your order. Find a store to view local store hours or see checkout for estimated delivery. A signature is required for delivery. Drivers may ask for verbal confirmation of receipt from a safe distance to satisfy the signature requirement. See https://www.apple.com/shop/shipping-pickup/ for more information.</p>
          <p>3. Trade-in values will vary based on the condition, year, and configuration of your eligible trade-in device. Not all devices are eligible for credit. You must be at least the age of majority to be eligible to trade in for credit or for an Apple Gift Card. Trade-in value may be applied toward qualifying new device purchase, or added to an Apple Gift Card. Actual value awarded is based on receipt of a qualifying device matching the description provided when estimate was made. Sales tax may be assessed on full value of a new device purchase. In-store trade-in requires presentation of a valid photo ID (local law may require saving this information). Offer may not be available in all stores, and may vary between in-store and online trade-in. Some stores may have additional requirements. Apple or its trade-in partners reserve the right to refuse, cancel, or limit quantity of any trade-in transaction for any reason. More details are available from Apple’s trade-in partner for trade-in and recycling of eligible devices. Restrictions and limitations may apply.</p>
          <p>4. AT&T iPhone 16 Special Deal: Monthly price (if shown) reflects net monthly payment, after application of AT&T trade-in credit applied over 36 months with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus, and trade-in of eligible smartphone. Receive credit with purchase of an iPhone 16 Pro or iPhone 16 Pro Max of either $1000, $830, or $350 (based upon the model and condition of your trade-in smartphone). Receive credit with purchase of an iPhone 16 or iPhone 16 Plus, of either $800, or $350 (based upon the model and condition of your trade-in smartphone). Max bill credits will not exceed the cost of the device. Requires upgrade of an existing line or activation of a new line and purchase of a new iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus, on qualifying 36 month 0% APR installment plan, subject to carrier credit qualification. Customers purchasing this offer through Apple cannot add the Next Up Anytime option. $0 down for well qualified customers only, or down payment may be required and depends on a variety of factors. Tax on full retail price due at sale. Requires activation on eligible AT&T unlimited plan. AT&T may temporarily slow data speeds if the network is busy. If you cancel eligible wireless service, credits will stop and you will owe the remaining device balance. Activation/Upgrade Fee: $35. Trade in device may not be on existing installment plan. Bill credits are applied as a monthly credit over the 36 month installment plan. Credits start within 3 bills. Will receive catchup credits once credits start. Wireless line must be on an installment agreement, active, and in good standing for 30 days to qualify. Installment agreement starts when device is shipped. To get all credits, device must remain on agreement for entire term and you must keep eligible service on device for entire installment term. Limited time offer; subject to change. Limits: one trade-in per qualifying purchase and one credit per line. May not be combinable with other offers, discounts, or credits. Purchase, financing, other limits, and restrictions apply. Price for iPhone 16 and iPhone 16 Plus includes $30 AT&T connectivity discount. Activation required.</p>
          <p>AT&T iPhone 16e Special Deal: Buy an iPhone 16e 128 GB and get $383.36 in bill credits applied over 36 months. Buy an iPhone 16e 256 GB and get $303.36 in bill credits applied over 36 months. Buy an iPhone 16e 512 GB and get $323.36 in bill credits applied over 36 months. Requires upgrade of an existing line (or activation of a new line) and purchase on qualifying 36-month 0% APR installment plan, subject to carrier credit qualification. $0 down for well-qualified customers only, or down payment may be required and depends on a variety of factors. Tax on full retail price due at sale. Requires activation on eligible AT&T unlimited plan. AT&T may temporarily slow data speeds if the network is busy. If you cancel eligible wireless service, credits will stop and you will owe the remaining device balance. Activation/Upgrade Fee: $35. Bill credits are applied as a monthly credit over the 36-month installment plan. Credits start within 3 bills. Will receive catch-up credits once credits start. Wireless line must be on an installment agreement, active, and in good standing for 30 days to qualify. Installment agreement starts when device is shipped. To get all credits, device must remain on agreement for entire term and you must keep eligible service on device for entire installment term. Limited-time offer; subject to change. Limits: one credit per line. May not be combinable with other offers, discounts, or credits. Purchase, financing, other limits, and restrictions apply. Activation required.</p>
          <p>AT&T iPhone 15 Special Deal: Buy an iPhone 15 128 GB and get $441.36 in bill credits applied over 36 months. Buy an iPhone 15 256 GB and get $361.36 in bill credits applied over 36 months. Buy an iPhone 15 512 GB and get $381.36 in bill credits applied over 36 months. Requires upgrade of an existing line (or activation of a new line) and purchase on qualifying 36-month 0% APR installment plan, subject to carrier credit qualification. $0 down for well-qualified customers only, or down payment may be required and depends on a variety of factors. Tax on full retail price due at sale. Requires activation on eligible AT&T unlimited plan. AT&T may temporarily slow data speeds if the network is busy. If you cancel eligible wireless service, credits will stop and you will owe the remaining device balance. Activation/Upgrade Fee: $35. Bill credits are applied as a monthly credit over the 36-month installment plan. Credits start within 3 bills. Will receive catch-up credits once credits start. Wireless line must be on an installment agreement, active, and in good standing for 30 days to qualify. Installment agreement starts when device is shipped. To get all credits, device must remain on agreement for entire term and you must keep eligible service on device for entire installment term. Limited-time offer; subject to change. Limits: one credit per line. May not be combinable with other offers, discounts, or credits. Purchase, financing, other limits, and restrictions apply. Activation required.</p>
          <p>Boost Mobile iPhone 16 Special Deal: Buy an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus and get $1000 in bill credits (not to exceed the cost of the iPhone) applied over 36 months. No trade-in required. If you are trading in a device with this deal, trade-in value will be applied as additional bill credits over 36 months. Monthly price (if shown) reflects net monthly payment, after application of $1000 in bill credit (not to exceed the cost of the iPhone purchased) and trade-in credit (if applicable) applied over 36 months respectively. Requires activation of a new line, Boost Mobile Infinite Access plan and purchase on qualifying 36-month 0% APR installment plan, subject to carrier credit qualification. After making 12 installment payments, you may upgrade to a new iPhone and get up to $1000 in bill credits (not to exceed the cost of the iPhone) applied over 36 months for the new iPhone on the Infinite Access plan and purchase on new qualifying 36-month 0% APR installment plan, subject to carrier credit qualification. Tax on full retail price due at sale. If you cancel eligible wireless service, credits will stop and you will owe the remaining device balance. Bill credits are applied as a monthly credit over the 36-month installment plan. Trade-in credits start within 3 bills. Installment agreement starts when device is shipped. To get all credits, device must remain on agreement for entire term and you must keep eligible service on device for entire installment term. Limited-time offer; subject to change. Limits: one credit per line. May not be combined with other offers, discounts, or credits. Purchase, financing, other limits, and restrictions apply. Price for iPhone 16 and iPhone 16 Plus includes $30 Boost Mobile connectivity discount. Activation required.</p>
          <p>T-Mobile iPhone 16 Special Deal: Monthly price (if shown) reflects net monthly payment, after application of T-Mobile trade-in credit applied over 24 months with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus and trade-in of eligible smartphone.</p>
          <p>Existing customers: Receive credit with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus (based upon the model and condition of your trade-in smartphone) of $1000, $800, or $400 for customers on a Go5G Next plan (excluding 55, Military, First Responder plans) ($100+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on a Go5G Plus plan (excluding 55, Military, First Responder plans) ($85+/mo. plan after AutoPay discount if applicable); or $800, $600, or $300 for customers on a Go5G Next 55, Military, or First Responder plan ($85+/mo. plan after AutoPay discount if applicable); or $600 or $300 for customers on a Go5G Plus 55, Military, or First Responder plan ($75+/mo. plan after AutoPay discount if applicable); or $300 or $150 for customers on a Go5G, Magenta, Magenta MAX, or Essentials plan ($60+/mo. plan after AutoPay discount if applicable). Must be an existing T-Mobile customer.</p>
          <p>Add-a-Line customers: Receive credit with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus (based upon the model and condition of your trade-in smartphone) of $1000, $800, or $400 for customers on a Go5G Next plan (excluding 55, Military, First Responder plans) ($100+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on a Go5G Plus plan (excluding 55, Military, First Responder plans) ($85+/mo. plan after AutoPay discount if applicable); or $800, $600, or $300 for customers on a Go5G Next 55, Military, or First Responder plan ($85+/mo. plan after AutoPay discount if applicable); or $600 or $300 for customers on a Go5G Plus 55, Military, or First Responder plan ($75+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on an Essentials, Magenta/MAX or Go5G plan (excluding 55, Military, First Responder plans) ($60+/mo. plan after AutoPay discount if applicable); or $600 or $300 for customers on an Essentials 55 Choice, Magenta/MAX, or Go5G 55, Military, or First Responder plan ($45+/mo. plan after AutoPay discount if applicable). Must be a T-Mobile customer adding a new line to an existing T-Mobile account.</p>
          <p>New customers: Receive credit with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus (based upon the model and condition of your trade-in smartphone) of $1000, $800, or $400 for customers on a Go5G Next plan (excluding 55, Military, First Responder plans) ($100+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on a Go5G Plus plan (excluding 55, Military, First Responder plans) ($85+/mo. plan after AutoPay discount if applicable); or $800, $600, or $300 for customers on a Go5G Next 55, Military, or First Responder plan ($85+/mo. plan after AutoPay discount if applicable); or $600 or $300 for customers on a Go5G Plus 55, Military, or First Responder plan ($75+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on an Essentials or Go5G plan (excluding 55, Military, First Responder plans) ($60+/mo. plan after AutoPay discount if applicable; or $600 or $300 for customers on an Essentials 55 Choice, or Go5G 55, Military, or First Responder plan ($45+/mo. plan after AutoPay discount if applicable). Must be a new T-Mobile customer.</p>
          <p>Max bill credits will not exceed the cost of the device. Credit comprised of (i) Apple instant trade-in credit at checkout and (ii) T-Mobile monthly bill credits applied over 24 months. Allow 2 bill cycles from valid submission and validation of trade-in. Tax on pre-credit price due at sale. Limited-time; subject to change. Qualifying credit, data plan, and trade-in (e.g., iPhone 15 Pro Max) in good condition required. Max 4 promotions on any iPhone per account. May not be combinable with some offers, discounts, or promotions. Activation required. Contact T-Mobile before cancelling entire account to continue remaining bill credits, or credits stop & balance on required finance agreement is due. Bill credits end if you pay off early.</p>
          <p>T-Mobile iPhone 16e Special Deal: Monthly price (if shown) reflects net monthly payment, after application of T-Mobile trade-in credit applied over 24 months with purchase of an iPhone 16e and trade-in of eligible smartphone.</p>
          <p>Existing customers: Receive credit with purchase of an iPhone 16e (based upon the model and condition of your trade-in smartphone) of $899, $800, or $400 for customers on a Go5G Next plan (excluding 55, Military, First Responder plans)($100+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on a Go5G Plus plan (excluding 55, Military, First Responder plans) ($85+/mo. plan after AutoPay discount if applicable); or $800, $600, or $300 for customers on a Go5G Next 55, Military, or First Responder plan ($85+/mo. plan after AutoPay discount if applicable); or $600 or $300 for customers on a Go5G Plus 55, Military, or First Responder plan ($75+/mo. plan after AutoPay discount if applicable); or $300 or $150 for customers on a Go5G, Magenta, Magenta MAX, or Essentials plan ($60+/mo. plan after AutoPay discount if applicable). Must be an existing T-Mobile customer.</p>
          <p>Add-a-Line customers: Receive credit with purchase of an iPhone 16e (based upon the model and condition of your trade-in smartphone) of $899, $800, or $400 for customers on a Go5G Next plan (excluding 55, Military, First Responder plans) ($100+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on a Go5G Plus plan (excluding 55, Military, First Responder plans) ($85+/mo. plan after AutoPay discount if applicable); or $800, $600, or $300 for customers on a Go5G Next 55, Military, or First Responder plan ($85+/mo. plan after AutoPay discount if applicable); or $600 or $300 for customers on a Go5G Plus 55, Military, or First Responder plan ($75+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on an Essentials, Magenta/MAX or Go5G plan (excluding 55, Military, First Responder plans) ($60+/mo. plan after AutoPay discount if applicable); or $600 or $300 for customers on an Essentials 55 Choice, Magenta/MAX, or Go5G 55, Military, or First Responder plan ($45+/mo. plan after AutoPay discount if applicable). Must be a T-Mobile customer adding a new line to an existing T-Mobile account.</p>
          <p>New customers: Receive credit with purchase of an iPhone 16e (based upon the model and condition of your trade-in smartphone) of $899, $800, or $400 for customers on a Go5G Next plan (excluding 55, Military, First Responder plans) ($100+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on a Go5G Plus plan (excluding 55, Military, First Responder plans) ($85+/mo. plan after AutoPay discount if applicable); or $800, $600, or $300 for customers on a Go5G Next 55, Military, or First Responder plan ($85+/mo. plan after AutoPay discount if applicable); or $600 or $300 for customers on a Go5G Plus 55, Military, or First Responder plan ($75+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on an Essentials or Go5G plan (excluding 55, Military, First Responder plans) ($60+/mo. plan after AutoPay discount if applicable; or $600 or $300 for customers on an Essentials 55 Choice, or Go5G 55, Military, or First Responder plan ($45+/mo. plan after AutoPay discount if applicable). Must be a new T-Mobile customer.</p>
          <p>Max bill credits will not exceed the cost of the device. Credit comprised of (i) Apple instant trade-in credit at checkout and (ii) T-Mobile monthly bill credits applied over 24 months. Allow 2 bill cycles from valid submission and validation of trade-in. Tax on pre-credit price due at sale. Limited-time; subject to change. Qualifying credit, data plan, and trade-in (e.g., iPhone 15 Pro Max) in good condition required. Max 4 promotions on any iPhone per account. May not be combinable with some offers, discounts, or promotions. Activation required. Contact T-Mobile before cancelling entire account to continue remaining bill credits, or credits stop & balance on required finance agreement is due. Bill credits end if you pay off early.</p>
          <p>T-Mobile iPhone 15 Special Deal: Monthly price (if shown) reflects net monthly payment, after application of T-Mobile trade-in credit applied over 24 months with purchase of an iPhone 15 or iPhone 15 Plus and trade-in of eligible smartphone.</p>
          <p>Existing customers: Receive credit with purchase of an iPhone 15 or iPhone 15 Plus (based upon the model and condition of your trade-in smartphone) of $1000, $800, or $400 for customers on a Go5G Next plan (excluding 55, Military, First Responder plans) ($100+/mo. plan after AutoPay discount if applicable); or $800 or $400 for customers on a Go5G Plus plan (excluding 55, Military, First Responder plans) ($85+/mo. plan after AutoPay discount if applicable); or $800, $600, or $300 for customers on a Go5G Next 55, Military, or First Responder plan ($85+/mo. plan after AutoPay discount if applicable); or $600 or $300 for customers on a Go5G Plus 55, Military, or First Responder plan ($75+/mo. plan after AutoPay discount if applicable); or $300 or $150 for customers on a Go5G, Magenta, Magenta MAX, or Essentials plan ($60+/mo. plan after AutoPay discount if applicable). Must be an existing T-Mobile customer.</p>
          <p>Add-a-Line customers: Receive credit with purchase of an iPhone 15 or iPhone 15 Plus (based upon the model and condition of your trade-in smartphone) of $1000, $800, or $400 for customers on a Go5G Next plan (excluding 55, Military, First Responder plans); or $800 or $400 for customers on a Go5G Plus plan (excluding 55, Military, First Responder plans); or $800, $600, or $300 for customers on a Go5G Next 55, Military, or First Responder plan; or $600 or $300 for customers on a Go5G Plus 55, Military, or First Responder plan; or $800 or $400 for customers on an Essentials, Simple Choice, TMO ONE/Plus, Magenta/MAX or Go5G plan (excluding 55, Military, First Responder plans); or $600 or $300 for customers on an Essentials 55 Choice, TMO ONE/Plus, Magenta/MAX & Go5G 55, Military, or First Responder plan. Must be a T-Mobile customer adding a new line to an existing T-Mobile account.</p>
          <p>New customers: Receive credit with purchase of an iPhone 15 or iPhone 15 Plus(based upon the model and condition of your trade-in smartphone) of $1000, $800, or $400 for customers on a Go5G Next plan (excluding 55, Military, First Responder plans); or $800 or $400 for customers on a Go5G Plus plan (excluding 55, Military, First Responder plans); or $800, $600, or $300 for customers on a Go5G Next 55, Military, or First Responder plan; or $600 or $300 for customers on a Go5G Plus 55, Military, or First Responder plan; or $800 or $400 for customers on an Essentials or Go5G plan (excluding 55, Military, First Responder plans); or $600 or $300 for customers on an Essentials 55 Choice, or Go5G 55, Military, or First Responder plan. Must be a new T-Mobile customer.</p>
          <p>Max bill credits will not exceed the cost of the device. Credit comprised of (i) Apple instant trade-in credit at checkout and (ii) T-Mobile monthly bill credits applied over 24 months. Allow 2 bill cycles from valid submission and validation of trade-in. Tax on pre-credit price due at sale. Limited-time offer; subject to change. Qualifying credit, data plan, and trade-in in good condition required. Max 4 promotional offers on any iPhone per account. May not be combinable with some offers or discounts. Activation required.Contact T-Mobile before cancelling service to continue remaining bill credits on current device, or credits stop & balance on required finance agreement is due.</p>
          <p>Verizon iPhone 16 Special Deal: Monthly price (if shown) reflects net monthly payment, after application of Verizon trade-in credit applied over 36 months with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus.</p>
          <p>Existing customers: Customers on an Unlimited Ultimate plan (min. $90/mo w/Auto Pay (+taxes/fees) for 36 mos) receive: $1000 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16 Pro or iPhone 16 Pro Max; $930 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16 Plus; or $830 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16. Customers on an Unlimited Plus plan (min. $80/mo w/Auto Pay (+taxes/fees) for 36 mos) receive $830 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus. Customers on an Unlimited Welcome plan (min. $80/mo w/Auto Pay (+taxes/fees) for 36 mos) receive $600 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus. Must be an existing Verizon customer.</p>
          <p>New or Add-a-Line customers: Customers on an Unlimited Ultimate plan (min. $90/mo w/Auto Pay (+taxes/fees) for 36 mos) receive: $1000 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16 Pro or iPhone 16 Pro Max; $930 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16 Plus; or $830 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16. Customers on an Unlimited Plus plan (min. $80/mo w/Auto Pay (+taxes/fees) for 36 mos) receive $830 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus. Customers on an Unlimited Welcome plan (min. $80/mo w/Auto Pay (+taxes/fees) for 36 mos) receive $600 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus. Must be a new Verizon customer or adding a new line to an existing Verizon account.</p>
          <p>Max bill credits will not exceed the cost of the device. Credit comprised of (i) Apple instant trade-in credit at checkout and (ii) Verizon monthly bill credits applied over 36 months. Customer must remain in the Verizon Device Payment Program for 36 months to receive the full benefit of the Verizon bill credits. Bill credits may take 1-2 bill cycles to appear. If it takes two cycles for bill credits to appear, you'll see the credit for the first cycle on your second bill in addition to that month's credit. Requires purchase and activation of a new iPhone 16 Pro, iPhone 16 Pro Max, iPhone 16, or iPhone 16 Plus with the Verizon Device Payment Program at 0% APR for 36 months, subject to carrier credit qualification, and iPhone availability and limits. Taxes and shipping not included in monthly price. Sales tax may be assessed on full value of new iPhone. Requires eligible unlimited service plan. Requires trade-in of eligible device in eligible condition. Must be at least 18 to trade-in. Apple or its trade-in partners reserve the right to refuse or limit any trade-in transaction for any reason. In-store trade-in requires presentation of a valid, government-issued photo ID (local law may require saving this information). In-store promotion availability subject to local law; speak to a Specialist to learn more. Limited-time offer; subject to change. Additional terms from Apple, Verizon, and Apple's trade-in partners may apply. Price for iPhone 16 and iPhone 16 Plus includes $30 Verizon connectivity discount. Activation required.</p>
          <p>Verizon iPhone 16e Special Deal: Monthly price (if shown) reflects net monthly payment, after application of Verizon trade-in credit applied over 36 months with purchase of an iPhone 16e.</p>
          <p>Existing customers: Customers on an Unlimited Ultimate plan, Unlimited Plus plan, or Unlimited Welcome plan (min. $65/mo w/Auto Pay (+taxes/fees) for 36 mos) receive $600 credit (based upon the model and condition of your trade-in smartphone) with purchase of an iPhone 16e. Must be an existing Verizon customer.</p>
          <p>New or Add-a-Line customers: Customers on an Unlimited Ultimate plan, Unlimited Plus plan, or Unlimited Welcome plan (min. $65/mo w/Auto Pay (+taxes/fees) for 36 mos) receive $600 credit (based upon the model and condition of your trade-in smartphone) with purchase of a iPhone 16e. Must be a new Verizon customer or adding a new line to an existing Verizon account.</p>
          <p>Max bill credits will not exceed the cost of the device. Credit comprised of (i) Apple instant trade-in credit at checkout and (ii) Verizon monthly bill credits applied over 36 months. Customer must remain in the Verizon Device Payment Program for 36 months to receive the full benefit of the Verizon bill credits. Bill credits may take 1-2 bill cycles to appear. If it takes two cycles for bill credits to appear, you'll see the credit for the first cycle on your second bill in addition to that month's credit. Requires purchase and activation of a new iPhone 16e with the Verizon Device Payment Program at 0% APR for 36 months, subject to carrier credit qualification, and iPhone availability and limits. Taxes and shipping not included in monthly price. Sales tax may be assessed on full value of new iPhone. Requires eligible unlimited service plan. Requires trade-in of eligible device in eligible condition. Must be at least 18 to trade-in. Apple or its trade-in partners reserve the right to refuse or limit any trade-in transaction for any reason. In-store trade-in requires presentation of a valid, government-issued photo ID (local law may require saving this information). In-store promotion availability subject to local law; speak to a Specialist to learn more. Limited-time offer; subject to change. Additional terms from Apple, Verizon, and Apple's trade-in partners may apply. Activation required.</p>
          <p>⁺ New subscribers only. $10.99/month after trial. Offer is available for new Apple Music subscribers with a new eligible device for a limited time only. Offer redemption for eligible audio devices requires connecting or pairing to an Apple device running the latest iOS or iPadOS. Offer redemption for Apple Watch requires connecting or pairing to an iPhone running the latest iOS. Offer good for three months after eligible device activation. Only one offer per Apple Account, regardless of the number of eligible devices you purchase. Plan automatically renews until cancelled. Restrictions and other offerterms(Opens in a new window) apply.</p>
          <p>⁺⁺ Apple TV+ offer available to new and qualified returning subscribers only. $9.99/month after free trial. Only one offer per Apple Account and only one offer per family if you’re part of a Family Sharing group, regardless of the number of devices that you or your family purchase. This offer is not available if you or your family have previously accepted an Apple TV+ 3 months free or 1 year free offer. Offer good for 3 months after eligible device is activated. Plan automatically renews until cancelled. Restrictions and other terms apply.</p>
          <p>Apple Pay is a service provided by Apple Payments Services LLC, a subsidiary of Apple Inc. Neither Apple Inc. nor Apple Payments Services LLC is a bank. Any card used in Apple Pay is offered by the card issuer.</p>
          <p>We approximate your location from your internet IP address by matching it to a geographic region or from the location entered during your previous visit to Apple.</p>
        </div>
         <div className="max-w-[1000px] mx-auto px-4 py-8 space-y-8">
        {/* Top info text */}
        <div className="text-[12px]">
          <p>
            * Instant savings, otherwise referred to as instant cashback, is available with select payment modes only.
          </p>
        </div>

        {/* Links columns */}
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-4 text-[12px]">
          <div>
            <h3 className="font-semibold text-black mb-2">Shop and Learn</h3>
            <ul className="space-y-1">
              <li className='cursor-pointer'>Store</li>
              <li className='cursor-pointer'>Mac</li>
              <li className='cursor-pointer'>iPhone</li>
              <li className='cursor-pointer'>Watch</li>
              <li className='cursor-pointer'>iPad</li>
              <li className='cursor-pointer'>AirPods</li>
              <li className='cursor-pointer'>TV & Home</li>
            </ul>
          </div>
          <div>
            <h3 className="font-semibold text-black mb-2">Services</h3>
            <ul className="space-y-1">
              <li className='cursor-pointer'>Apple Music</li>
              <li className='cursor-pointer'>Apple TV+</li>
              <li className='cursor-pointer'>iCloud</li>
              <li className='cursor-pointer'>Apple One</li>
              <li className='cursor-pointer'>Apple Pay</li>
            </ul>
          </div>
          <div>
            <h3 className="font-semibold text-black mb-2">Account</h3>
            <ul className="space-y-1">
              <li className='cursor-pointer'>Manage Your Apple ID</li>
              <li className='cursor-pointer'>iCloud.com</li>
              <li className='cursor-pointer'>Apple Store Account</li>
            </ul>
          </div>
          <div>
            <h3 className="font-semibold text-black mb-2">Apple Store</h3>
            <ul className="space-y-1">
              <li className='cursor-pointer'>Find a Store</li>
              <li className='cursor-pointer'>Genius Bar</li>
              <li className='cursor-pointer'>Today at Apple</li>
              <li className='cursor-pointer'>Apple Camp</li>
              <li className='cursor-pointer'>Refurbished</li>
            </ul>
          </div>
          <div>
            <h3 className="font-semibold text-black mb-2">About Apple</h3>
            <ul className="space-y-1">
              <li className='cursor-pointer'>Newsroom</li>
              <li className='cursor-pointer'>Careers</li>
              <li className='cursor-pointer'>Investors</li>
              <li className='cursor-pointer'>Events</li>
              <li className='cursor-pointer'>Contact Apple</li>
            </ul>
          </div>
        </div>

        {/* Divider */}
        <hr className="border-t border-gray-300" />

        {/* Bottom section */}
        <div className="flex flex-col md:flex-row justify-between items-center text-[12px] text-[#6e6e73] pt-4">
          <p className="mb-2 md:mb-0">Copyright © 2025 Apple Inc. All rights reserved.</p>
          <div className="flex gap-4 flex-wrap justify-center md:justify-end ">
            <span className='cursor-pointer'>Privacy Policy</span>
            <span className='cursor-pointer'>Terms of Use</span>
            <span className='cursor-pointer'>Sales Policy</span>
            <span className='cursor-pointer'>Legal</span>
            <span className='cursor-pointer'>Site Map</span>
          </div>
        </div>
      </div>
      </div>
    </div>
  );
}

export default Footer;
